//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MagicShutdown.rc
//
#define IDCANCEL2                       3
#define IDOrder                         3
#define IDOnHelp                        3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MagicShutdown_DIALOG        102
#define IDS_STRINGMustReg               102
#define IDS_STRINGRegWrong              103
#define IDS_STRINGRegSuccessed          104
#define IDS_OrderURL                    105
#define IDS_DayConfig                   106
#define IDS_RPATTERN_REMOVE             106
#define IDS_WeeklyConfig                107
#define IDS_RPATTERN_ADD                107
#define IDR_MAINFRAME                   128
#define IDR_MNUTRAY                     129
#define IDI_ARROW                       130
#define IDI_ICON1                       133
#define IDI_ICON2                       134
#define IDI_ICON3                       135
#define IDI_ICON4                       136
#define IDI_ICON5                       137
#define IDI_ICON6                       138
#define IDI_ICON7                       139
#define IDI_ICON8                       140
#define IDI_ICON9                       141
#define IDI_ICON10                      142
#define IDI_ICON11                      143
#define IDI_ICON12                      144
#define IDI_ICON13                      145
#define IDI_ICON14                      146
#define IDI_ICON15                      147
#define IDI_ICONBLANK                   148
#define IDB_IMAGES_SMALL                152
#define IDB_IMAGES_NORMAL               153
#define IDR_MENUOP                      154
#define IDD_SN                          155
#define IDI_ICON22                      162
#define IDI_ICON16                      171
#define IDD_Daily                       172
#define IDD_Yearly2                     174
#define IDD_Yearly                      174
#define IDD_Monthly2                    175
#define IDD_Monthly                     175
#define IDD_Countdown                   176
#define IDB_TABCTRL_IMAGE               177
#define IDB_ActionList                  183
#define IDC_DATEOFF                     1001
#define IDC_TIMEOFF                     1002
#define IDC_RDOSWOFF                    1003
#define IDC_RDOLOGOFF                   1004
#define IDC_RDOLOGOFFTIMER              1005
#define IDC_EDTMINCNT                   1006
#define IDC_EDTSECCNT                   1007
#define IDC_RDOSWOFFTIMER               1008
#define IDC_SPNMINCNT                   1009
#define IDC_SPNSECCNT                   1010
#define IDC_RDONOTHING                  1011
#define IDC_BTNAPPLY                    1012
#define IDC_BTNPAUSE                    1013
#define IDC_LBLMIN                      1014
#define IDC_LBLSEC                      1015
#define IDC_RDORESTART                  1016
#define IDC_AddSound                    1016
#define IDC_OpenFile                    1016
#define IDC_RDORESTARTTIMER             1017
#define IDC_OpenFile2                   1017
#define IDC_FRAOPT                      1018
#define IDC_LBLMIN2                     1018
#define IDC_SLIDER1                     1021
#define IDC_SLIDER                      1021
#define IDC_EMAIL                       1027
#define IDC_Staic                       1028
#define IDRegNow                        1029
#define IDC_ISN                         1030
#define IDC_UserName                    1031
#define IDC_TAB                         1032
#define IDC_RADIO1                      1033
#define IDRegNow4                       1033
#define IDC_Option                      1033
#define IDC_RADIO2                      1034
#define IDC_EDIT1                       1035
#define IDC_RADIO3                      1036
#define IDC_CHECK1                      1036
#define IDC_No67                        1036
#define IDC_RADIO_No67                  1036
#define IDC_RADIO4                      1037
#define IDC_CHECK2                      1037
#define IDC_RADIOSetDay                 1037
#define IDC_CHECK3                      1038
#define IDC_COMBO1                      1038
#define IDC_RADIO5                      1038
#define IDC_RADIONo7                    1038
#define IDC_RADIO_No7                   1038
#define IDC_COMBOActionList             1038
#define IDC_CHECK4                      1039
#define IDC_COMBO2                      1039
#define IDC_SPIN1                       1039
#define IDC_RADIO_Only7                 1039
#define IDC_CHECK5                      1040
#define IDC_COMBO3                      1040
#define IDC_COMBOYearS                  1040
#define IDC_RADIO_Only6                 1040
#define IDC_CHECK6                      1041
#define IDC_COMBO4                      1041
#define IDC_COMBOYearD                  1041
#define IDC_RADIO_Only67                1041
#define IDC_CHECK7                      1042
#define IDC_DATETIMEPICKER1             1042
#define IDC_DATETIMEPICKER_DailyDate    1042
#define IDC_DATETIMEPICKERYears         1042
#define IDC_DATEAutoShutdown            1042
#define IDC_EDIT2                       1043
#define IDC_Countdown                   1043
#define IDC_CHECK8                      1043
#define IDC_EDIT4                       1044
#define IDC_YearS                       1044
#define IDC_DATECountDown               1044
#define IDC_YearD                       1045
#define IDC_EDITYearS                   1046
#define IDC_RADIO                       1047
#define IDC_RADIOEachDay                1047
#define IDC_EveryDay                    1049
#define IDC_RADIO_EveryDay              1049
#define IDC_COMBO_Month2_Days           1052
#define IDC_IsForceClose                1053
#define IDC_CUSTOM1                     1054
#define IDC_TimeShow                    1055
#define IDC_TimeShow2                   1056
#define FileOpen                        1537
#define IDD_Weekly                      1545
#define ID_POP_Play                     32770
#define ID_POP_EXIT                     32771
#define ID_POP_Restore                  32777
#define ID_POP_Delete                   32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
